// Code generated by protoc-gen-go.
// source: auth.proto
// DO NOT EDIT!

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	SignupOrLoginRequest
	AuthResponse
	UpdateRequest
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignupOrLoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *SignupOrLoginRequest) Reset()                    { *m = SignupOrLoginRequest{} }
func (m *SignupOrLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*SignupOrLoginRequest) ProtoMessage()               {}
func (*SignupOrLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AuthResponse struct {
	UserId uint64 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type UpdateRequest struct {
	Username    string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	OldPassword string `protobuf:"bytes,2,opt,name=oldPassword" json:"oldPassword,omitempty"`
	NewPassword string `protobuf:"bytes,3,opt,name=newPassword" json:"newPassword,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*SignupOrLoginRequest)(nil), "SignupOrLoginRequest")
	proto.RegisterType((*AuthResponse)(nil), "AuthResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Auth service

type AuthClient interface {
	Signup(ctx context.Context, in *SignupOrLoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Login(ctx context.Context, in *SignupOrLoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Signup(ctx context.Context, in *SignupOrLoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/Auth/Signup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Login(ctx context.Context, in *SignupOrLoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/Auth/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/Auth/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	Signup(context.Context, *SignupOrLoginRequest) (*AuthResponse, error)
	Login(context.Context, *SignupOrLoginRequest) (*AuthResponse, error)
	Update(context.Context, *UpdateRequest) (*AuthResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupOrLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Signup(ctx, req.(*SignupOrLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupOrLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*SignupOrLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _Auth_Signup_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Auth_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x87, 0x8d, 0xd6, 0xa0, 0xa3, 0x15, 0x09, 0x2a, 0x65, 0x4f, 0x25, 0x07, 0xd1, 0x4b, 0x14,
	0x7d, 0x02, 0x7b, 0x13, 0x44, 0x4b, 0xc4, 0xb3, 0xc4, 0x66, 0xd8, 0x16, 0x34, 0x89, 0xf9, 0x43,
	0x5f, 0xc4, 0x07, 0x96, 0x24, 0x5a, 0x76, 0xd1, 0xc3, 0x1e, 0x7f, 0x99, 0x6f, 0x32, 0xf3, 0x31,
	0x00, 0x2a, 0xc5, 0xa5, 0x70, 0xde, 0x46, 0xcb, 0x1f, 0xe1, 0xe4, 0x79, 0xd5, 0x9a, 0xe4, 0x9e,
	0xfc, 0x83, 0x6d, 0x57, 0x46, 0xe2, 0x67, 0xc2, 0x10, 0x59, 0x03, 0x7b, 0x29, 0xa0, 0x37, 0xea,
	0x03, 0x27, 0x64, 0x4a, 0x2e, 0xf6, 0xe5, 0x26, 0xe7, 0x9a, 0x53, 0x21, 0xac, 0xad, 0xd7, 0x93,
	0xed, 0x5a, 0xfb, 0xcd, 0xfc, 0x1c, 0x0e, 0xef, 0x52, 0x5c, 0x4a, 0x0c, 0xce, 0x9a, 0x80, 0xec,
	0x0c, 0x68, 0xee, 0xbb, 0xd7, 0xe5, 0x97, 0x91, 0xfc, 0x49, 0xdc, 0xc2, 0xf8, 0xc5, 0x69, 0x15,
	0x71, 0xc8, 0xc0, 0x29, 0x1c, 0xd8, 0x77, 0x3d, 0xef, 0xcf, 0xec, 0x3e, 0x65, 0xc2, 0xe0, 0x7a,
	0x43, 0xec, 0x54, 0xa2, 0xf3, 0x74, 0xf3, 0x45, 0x60, 0x94, 0x37, 0x63, 0xd7, 0x40, 0xab, 0x31,
	0x3b, 0x15, 0xff, 0xa9, 0x37, 0x63, 0xd1, 0x35, 0xe0, 0x5b, 0xec, 0x0a, 0x76, 0x0b, 0x30, 0xb8,
	0xe1, 0x12, 0x68, 0x95, 0x63, 0x47, 0xa2, 0x67, 0xf9, 0x07, 0x9d, 0x35, 0x70, 0xdc, 0x7a, 0xb7,
	0x78, 0x5d, 0xa0, 0x89, 0xe8, 0x45, 0xbe, 0xcc, 0xac, 0xec, 0x39, 0x27, 0x6f, 0xb4, 0x9c, 0xe8,
	0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x72, 0xe9, 0x38, 0xb0, 0x01, 0x00, 0x00,
}
